source:      .
destination: ./_site
includes:    ./_includes
# baseurl:

collections:
  projects:
    output: true

# Statable visitor analytics and public map widget.
statable_public_hash: "q768970cbB"
statable_site_id: "3270462"
